### ISSUE TITLE
Implement User Management System

### ISSUE THREAD

**Issue by V-ed** [ved-websites/fullstacked#64]
## TODOs

- [x] Add basic user management page
	- [x] Set page to allow for user edits
- [x] Create registration process
	- [x] Send email with proper link to register
		- [x] Properly setup DNS handling (https://github.com/Sh4yy/vercel-email#setup-spf)
		- [x] Test sending email on create user

## Interesting Resources

https://github.com/carstenlebek/svelte-email
https://github.com/Sh4yy/vercel-email

**Comment by V-ed** [comment]
closed by 6d1c2083956e0abfdf8b5349301c378163098292
